using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Euler_2
{
	//Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:

	//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms
	class Program
	{
		static void Main(string[] args)
		{
			var result = Fibonacci(400000);
			Console.WriteLine($"The sum of all even values below 4,000,000 are {result}");
			Console.ReadLine();
		}

		public static long Fibonacci(long count)
		{
			int first = 1;
			int second = 1;
			int result = first + second;
			int evenTerms = 0;

			for (int i = 0; i < count; i++)
			{
				if (result % 2 == 0)
					evenTerms += result;

				first = second;
				second = result;
				result = first + second;

				if(result >= 4000000)
					break;
			}

			return evenTerms;
		}
	}
}
